// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

String decrypt(
        {required String key, required String ciphertext, dynamic hint}) =>
    RustLib.instance.api.decrypt(key: key, ciphertext: ciphertext, hint: hint);

String encrypt({required String key, required String message, dynamic hint}) =>
    RustLib.instance.api.encrypt(key: key, message: message, hint: hint);
